// <auto-generated />
namespace RMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CEFinal_MArks_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CEFinal_MArks_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201805290810207_CE,Final_MArks_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
