// <auto-generated />
namespace RMS.DAL.RMSMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SomeDataValidationsAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SomeDataValidationsAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201805101908363_SomeDataValidationsAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
