// <auto-generated />
namespace RMS.DAL.RMSMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_instructor_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_instructor_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201805180908076_User_instructor_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
